// Runs automatically before every `npm run dev` and `npm run build`
// (see package.json "predev"/"prebuild"). Stamps the current build with a
// unique version string so the app can tell a running tab apart from a
// freshly-deployed version — see components/UpdateAvailableBanner.jsx.
const fs = require("fs");
const path = require("path");

const pkg = require("../package.json");
const version = `${pkg.version}-${Date.now()}`;

// 1) public/version.json — fetched at runtime by open tabs to check for updates.
fs.writeFileSync(
  path.join(__dirname, "..", "public", "version.json"),
  JSON.stringify({ version }, null, 2) + "\n"
);

// 2) lib/buildVersion.generated.js — baked into THIS build's JS bundle, so
//    a tab always knows which version it's currently running.
fs.writeFileSync(
  path.join(__dirname, "..", "lib", "buildVersion.generated.js"),
  `// Auto-generated by scripts/gen-version.js — do not edit by hand.\nexport const BUILD_VERSION = ${JSON.stringify(version)};\n`
);

console.log(`[gen-version] stamped build ${version}`);
